import { PALETTE_COLORS } from '@/config/theme';
import { SxProps } from '@mui/material';

export const HeroPageStyle: SxProps = {
  minHeight: '70vh',
  width: '100%',
  margin: 0,
  padding: 0,
  bgcolor: PALETTE_COLORS.pine,
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  '& #container': {
    width: { xs: '90%', sm: '85%', md: '80%', lg: '75%' },
    height: '100%',
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'flex-end',
    mt: 7,
  },
  '& #container > .content-image': {
    flexBasis: { xs: '100%', sm: '100%', md: '50%' },
    mt: { xs: '10px', sm: '10px', md: '0' },
    mb: { xs: '30px', sm: '30px', md: '0' },
  },
  '& #container > .content': {
    flexBasis: { xs: '100%', sm: '100%', md: '50%' },
    mt: { xs: '10px', sm: '10px', md: '0' },
    mb: { xs: '30px', sm: '30px', md: '0' },
    display: 'flex',
    flexDirection: 'column',
    alignItems: { xs: 'center', sm: 'center', md: 'flex-start' },
    textAlign: { xs: 'center', sm: 'center', md: 'left' },
  },
  '& .MuiTypography-root': {
    color: 'white',
  },
  '& #container .MuiListItem-root': {
    padding: 0,
    mb: 3,
  },
  '& #container .MuiListItem-root svg': {
    color: 'white',
  },
  '& .image-container': {
    height: '100%',
    overflow: 'hidden',
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  '& .box-image img': {
    borderRadius: '10px',
    width: { xs: '90%', sm: '80%', md: '90%', lg: '100%' },
    maxWidth: { sm: '500px', lg: '100%' },
    height: 'auto',
    aspectRatio: '16 / 9',
    objectFit: 'cover',
    margin: '0 auto',
    display: 'block',
  },
  '.box-image-template': {
    height: '375px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  '.hero-title': {
    mb: 4,
    fontWeight: 'bold',
    fontSize: { xs: '1.6rem', sm: '1.8rem', md: '1.8rem', lg: '2.5rem' },
    mr: '10px',
  },
};

export const FAQStyle: SxProps = {
  minHeight: '80vh',
  width: '100%',
  margin: 0,
  padding: 0,
  bgcolor: PALETTE_COLORS.white,
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  flexDirection: 'column',
  '& #faq-container': {
    width: { xs: '55%', sm: '50%', md: '45%', lg: '40%' },
    padding: 0,
  },
  '& #faq-container > .faq-title': {
    textAlign: 'center',
    mb: '5px',
    color: PALETTE_COLORS.neon_orange,
    fontWeight: 'bold',
    fontSize: { xs: '1.6rem', sm: '1.8rem', md: '1.8rem', lg: '2.5rem' },
  },
  '& #faq-container .accordion-text': {
    fontSize: { xs: '0.8rem', sm: '1rem', lg: '1rem' },
  },
  '& #faq-container .accordion': {
    borderRadius: '10px',
    mb: '5px',
    padding: 0,
    boxShadow: '0px 0px 10px rgba(0, 0, 0, 0.6)',
    border: 'none',
    overflow: 'hidden',
  },
  '& #faq-container .MuiAccordion-root svg': {
    color: PALETTE_COLORS.pine,
    fontSize: 30,
  },
  '#change-container': {
    width: '90%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    mt: 6,
    mb: 4,
    textAlign: 'center',
  },
  '#change-container .MuiTypography-root': {
    color: PALETTE_COLORS.neon_orange,
    mb: 4,
    fontWeight: 'bold',
  },
  '.change-text': {
    fontSize: { xs: '1.6rem', sm: '1.8rem', md: '1.8rem', lg: '2.5rem' },
  },
  '.input-change-text': {
    fontSize: { xs: '1.6rem', sm: '1.8rem', md: '1.8rem', lg: '2.5rem' },
    mb: 2,
  },
};

export const RoofDiagnosticsStyle: SxProps = {
  minHeight: '60vh',
  width: '100%',
  margin: 0,
  padding: 0,
  bgcolor: PALETTE_COLORS.pine,
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  '& #diagnostics-container': {
    width: { xs: '90%', sm: '85%', md: '80%', lg: '75%' },
    height: '100%',
    display: 'flex',
    flexWrap: { xs: 'wrap', md: 'nowrap' },
    gap: { md: '32px' },
    alignItems: 'center',
  },
  '& #diagnostics-container > .content-text': {
    flexBasis: { xs: '100%', sm: '100%' },
    mt: { xs: '10px', sm: '10px', md: '0' },
    mb: { xs: '30px', sm: '30px', md: '0' },
    display: 'flex',
    flexGrow: { md: 1 },
    flexDirection: 'column',
    alignItems: { xs: 'center', sm: 'center', md: 'flex-start' },
    textAlign: { xs: 'center', sm: 'center', md: 'left' },
  },
  '& #diagnostics-container > .content-img': {
    flexBasis: { xs: '100%', sm: '100%' },
    flexGrow: { md: 1 },
    mt: { xs: '10px', sm: '10px', md: '0' },
    mb: { xs: '30px', sm: '30px', md: '0' },
  },
  '& .MuiTypography-root': {
    color: 'white',
    mb: 2,
  },
  '& .image-container': {
    height: '100%',
    overflow: 'hidden',
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  '& .image-container img': {
    borderRadius: '10px',
    width: { xs: '90%', sm: '80%', md: '90%', lg: '100%' },
    maxWidth: { sm: '500px', lg: '100%' },
    height: 'auto',
    aspectRatio: '16 / 9',
    objectFit: 'cover',
    margin: '0 auto',
    display: 'block',
  },
  '.diagnostics-title': {
    mb: 4,
    color: PALETTE_COLORS.cream,
    fontWeight: 'bold',
    fontSize: { xs: '1.6rem', sm: '1.8rem', md: '1.8rem', lg: '2.5rem' },
  },
  '.diagnostics-description': {
    fontSize: { xs: '0.8rem', sm: '1rem', lg: '1rem' },
    mb: 2,
    mr: '10px',
    textAlign: 'justify',
  },
};

export const FooterTemplateStyle: SxProps = {
  minHeight: '45vh',
  height: 'auto',
  width: '100%',
  margin: 0,
  padding: 0,
  bgcolor: PALETTE_COLORS.cream,
  display: 'flex',
  alignItems: 'center',
  flexDirection: 'column',
  '& #footer-container': {
    width: { xs: '90%', sm: '85%', md: '55%', lg: '45%' },
    padding: 0,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
    textAlign: 'center',
  },
  '& #footer-container > .footer-title': {
    textAlign: 'center',
    color: PALETTE_COLORS.neon_orange,
    fontWeight: 'bold',
    fontSize: { xs: '1.6rem', sm: '1.8rem', md: '1.8rem', lg: '2.5rem' },
    mb: 3,
    mt: 4,
  },
  h6: {
    fontSize: { xs: '0.8rem', sm: '1rem', lg: '1rem' },
    mb: 7,
  },
  '.grid-footer': {
    justifyContent: 'center',
    alignItems: 'center',
    width: '65%',
    pb: 4,
  },
  '.stack-footer': {
    justifyContent: 'center',
    pb: 1,
    mb: 2,
    borderBottom: '2px solid',
    color: PALETTE_COLORS.forest,
  },
  '.footer-link': {
    fontWeight: 'bold',
    color: PALETTE_COLORS.black,
    textDecoration: 'none',
    fontSize: { xs: '1rem', sm: '1rem', md: '1.1rem', lg: '1.2rem' },
    '&:hover': {
      color: PALETTE_COLORS.neon_orange,
    },
  },
  '& #space-bottom': {
    bgcolor: PALETTE_COLORS.white,
    height: '80px',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  '.footer-h6': {
    fontSize: { xs: '0.8rem', sm: '1rem', lg: '1rem' },
    mb: 7,
  },
  '.button-json': {
    bgcolor: PALETTE_COLORS.neon_orange,
    height: '40px',
  },
};
