name: ci

on:
  push:
    branches: ['main', 'preprod']
  pull_request:
    branches: ['main', 'preprod']

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.x

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Prettier
        run: npm run format:check

      - name: Run Eslint
        run: npm run lint

      - name: Run Build
        run: npm run build

  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0

      - name: Install npm dependencies
        run: npm i --legacy-peer-deps

      - name: Build app
        run: npm run build
