name: Edit Page from Generated Base64

on:
  workflow_dispatch:
    inputs:
      jsonString:
        description: 'Le contenu du fichier généré'
        required: true
        type: string

jobs:
  update-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.x

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Set up Git
        run: |
          git config user.name "AmourRamanantsiresy"
          git config user.email "hei.amour.2@gmail.com"

      - name: Update the json data file
        run: |
          ./edit-existing-template.sh "${{ github.event.inputs.jsonString }}"
